// SPDX-FileCopyrightText: Azahar Emulator Project
// Copyright(c) 2026: Raibatsu (hello@raibatsu.com)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include <optional>
#include <string_view>

// Offline title metadata lookup, bundled entirely into the .nro (see titledb.bin, generated by
// tools/gen_titledb.py from GameTDB's 3dstdb.xml) - no network, no per-game fetch, just a binary
// search over a small in-memory index. See titledb.cpp for the exact binary layout.
namespace SwitchFrontend {

// Reads titledb.bin from romfs into memory once. Cheap (a few MB at most), safe to call more than
// once (a no-op after the first attempt, success or failure). Call once at boot.
void LoadTitleDatabase();

// Every field GameTDB has for one title. String fields are empty (not absent) when GameTDB has no
// value for them - always check .empty() rather than treating any field as guaranteed present.
// release_year is 0 if GameTDB has no release date on record.
struct TitleInfo {
    std::string_view developer;
    std::string_view publisher;
    std::string_view genre;             // comma-separated, e.g. "adventure,role-playing"
    std::string_view region;            // e.g. "NTSC-U", "PAL"
    std::string_view languages;         // comma-separated language codes, e.g. "EN,FR,DE"
    std::string_view rating_type;       // e.g. "ESRB", "CERO", "PEGI"
    std::string_view rating_value;      // e.g. "E", "A", "7"
    std::string_view rating_descriptors; // comma-separated, e.g. "mild cartoon violence"
    std::string_view wifi_features;     // comma-separated, e.g. "online"
    std::string_view synopsis;
    int release_year = 0;
    int release_month = 0;
    int release_day = 0;
    int wifi_players = 0;
    int input_players = 0;
};

// O(log n) binary search by the 4-character GameTDB game ID - the same ID gametdb.cpp's box art
// lookup uses, and the last 4 characters of a title's NCCH product code (see
// GameTdbGameId() in menu_data.h). std::nullopt if the database isn't loaded, `game_id` isn't
// exactly 4 characters, or there's no entry for it. Every string_view in the result stays valid
// for the life of the process (backed by a buffer that's never freed once loaded).
std::optional<TitleInfo> GetTitleInfo(std::string_view game_id, int cfg_language);

} // namespace SwitchFrontend
