#!/usr/bin/env python3
# SPDX-FileCopyrightText: Azahar Emulator Project
# Copyright(c) 2026: PalindromicBreadLoaf(palindromicbreadloaf@tuta.com)
# SPDX-License-Identifier: GPL-2.0-or-later

"""Regenerates src/citra_switch/rail_icons.h from the upstream Lucide icon set.

Fetches the SVG for each nav-rail tab, rasterizes it to a kSize*kSize 8-bit
coverage mask, and emits them as a C++ header.

    ./tools/gen_rail_icons.py

Requires ImageMagick built against librsvg and Pillow.
"""

import subprocess
import sys
import tempfile
import textwrap
import urllib.request
from pathlib import Path

from PIL import Image

SIZE = 32
UPSTREAM = "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/{}.svg"
DEST = Path("src/citra_switch/rail_icons.h")

ICONS = [
    ("Library", "layout-grid"),
    ("Install", "download"),
    ("Settings", "sliders-horizontal"),
    ("Paths", "folder"),
]

HEADER = """
// Generated by tools/gen_rail_icons.py. Do not edit by hand.
//
// Coverage masks rasterized from the Lucide icon set (https://lucide.dev),
// used under the ISC License.
//
//   Copyright (c) 2026 Lucide Icons and Contributors
//
//   Permission to use, copy, modify, and/or distribute this software for any
//   purpose with or without fee is hereby granted, provided that the above
//   copyright notice and this permission notice appear in all copies.
//
//   THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
//   WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
//   ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
//   WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
//   ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
//   OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//
// The "download" glyph derives from Feather (https://feathericons.com),
// Copyright (c) 2013-present Cole Bemis, under the MIT License.

#pragma once

#include <cstdint>

namespace SwitchFrontend::RailIcons {{

constexpr int kSize = {size};
"""


def rasterize(slug: str, workdir: Path) -> list[int]:
    """Fetch one SVG and return its alpha channel as a flat mask."""
    svg = workdir / f"{slug}.svg"
    png = workdir / f"{slug}.png"
    with urllib.request.urlopen(UPSTREAM.format(slug), timeout=30) as resp:
        svg.write_bytes(resp.read())

    # Rasterize at 4x and filter down.
    subprocess.run(
        ["magick", "-background", "none", "-density", "384", f"SVG:{svg}",
         "-resize", f"{SIZE}x{SIZE}", f"PNG32:{png}"],
        check=True,
    )
    image = Image.open(png).convert("RGBA")
    if image.size != (SIZE, SIZE):
        raise SystemExit(f"{slug}: expected {SIZE}x{SIZE}, got {image.size}")
    return list(image.getchannel("A").tobytes())


def main() -> int:
    if not DEST.parent.is_dir():
        raise SystemExit(f"run me from the repository root ({DEST.parent} not found)")

    chunks = [HEADER.format(size=SIZE)]
    with tempfile.TemporaryDirectory() as tmp:
        for name, slug in ICONS:
            mask = rasterize(slug, Path(tmp))
            covered = sum(1 for value in mask if value)
            print(f"{slug:22s} {covered:4d}/{SIZE * SIZE} px covered", file=sys.stderr)
            body = textwrap.fill(
                ", ".join(str(value) for value in mask),
                width=96, initial_indent="    ", subsequent_indent="    ",
            )
            chunks.append(
                f"// lucide/{slug}\nconstexpr std::uint8_t k{name}[kSize * kSize] = {{\n{body}\n}};\n"
            )

    chunks.append("} // namespace SwitchFrontend::RailIcons")
    DEST.write_text("\n".join(chunks) + "\n")
    print(f"wrote {DEST} ({DEST.stat().st_size} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
