// SPDX-FileCopyrightText: Azahar Emulator Project
// Copyright(c) 2026: PalindromicBreadLoaf(palindromicbreadloaf@tuta.com)
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated by font/bake_overlay_font.py from Roboto-Regular.ttf (Apache-2.0). Do not edit by hand.
//
// See the above file for more information.

#pragma once

namespace Vulkan::OverlayFont {

struct Glyph {
    float u0, v0, u1, v1;      // Atlas texture coordinates.
    float xoff, yoff;          // Bake-pixel offset from the pen to the quad.
    float w, h;                // Quad size in bake pixels.
    float xadvance;            // Horizontal pen advance in bake pixels.
};

constexpr int kFirstChar = 32;
constexpr int kLastChar = 126;
constexpr int kGlyphCount = 95;

constexpr int kAtlasWidth = 512;
constexpr int kAtlasHeight = 264;

constexpr float kBakePixelHeight = 48.0;
constexpr float kAscent = 45.0;
constexpr float kDescent = 12.0;
constexpr float kLineHeight = 57.0;

constexpr float kWhiteU = 0.076172f;
constexpr float kWhiteV = 0.928030f;

extern const Glyph kGlyphs[kGlyphCount];
extern const unsigned char kAtlas[kAtlasWidth * kAtlasHeight];

// Returns the glyph for a character folding anything outside the baked range to space.
inline const Glyph& GlyphFor(char c) {
    const int code = static_cast<unsigned char>(c);
    const int index = (code < kFirstChar || code > kLastChar) ? 0 : code - kFirstChar;
    return kGlyphs[index];
}

} // namespace Vulkan::OverlayFont
